Add identification for emails in HTML format
CybercentreCanada/assemblyline-base pull request #1343
Opened 2023-09-05 19:16 UTC by cccs-rs

Will be used by Frankenstrings (reject) and EmlParser (accept) to distinguish the difference between plain HTML and HTML formatted to represent an email.

2023-09-05 19:23 UTC, cccs-kevin requested changes
messaged details

2023-09-05 20:00 UTC, cccs-kevin approved these changes

2023-09-05 20:34 UTC, cccs-jh reviewed
This rule has a really large overlap with the document_email_1 rule. Could this be refactored to use that rule with a condition like `(code_html or code_html_2 or code_html_3) and (document_email_1 or document_email_2)`?

2023-09-06 11:20 UTC, cccs-rs commented
> This rule has a really large overlap with the document_email_1 rule. Could this be refactored to use that rule with a condition like `(code_html or code_html_2 or code_html_3) and (document_email_1 or document_email_2)`?
The spaces in `document_email_1` break the detection

2023-09-06 13:05 UTC, cccs-jh commented
> > This rule has a really large overlap with the document_email_1 rule. Could this be refactored to use that rule with a condition like `(code_html or code_html_2 or code_html_3) and (document_email_1 or document_email_2)`?
> 
> The spaces in `document_email_1` break the detection

I think we can remove the spaces from `document_email_1` without causing false positives. We don't rely on them to distinguish anything except between html and plaintext emails. If a misclassified html email ends up as `document/email` instead of `code/html` I think it is a better failure case since we want emlparser to run.

2023-09-07 17:44 UTC, merged