Adds
CybercentreCanada/assemblyline-base pull request #1382
Opened 2023-10-04 16:15 UTC by LukeL-dev

2023-10-16 13:05 UTC, cccs-rs requested changes

2023-10-16 13:05 UTC, cccs-rs commented on assemblyline/odm/models/config.py
> +    "enabled": True,
Probably a good idea to set the default for `enabled: False` in cases where deployments don't have SAML auth setup.

2023-10-16 20:26 UTC, cccs-sgaron commented
Also, is the corresponding PR ready in UI?

2024-05-27 18:48 UTC, cccs-sgaron commented
Superseeded by this https://github.com/CybercentreCanada/assemblyline-base/pull/1674

2024-05-27 18:48 UTC, closed without merging