Common cert module
CybercentreCanada/assemblyline-base pull request #169
Opened 2021-04-07 18:42 UTC by cccs-dawson

Changes to tagging.py and compat_tag_map.py:
	--add a FileJar class/object to the File model
	--FileJar has tags for the main_class and main_package to be pulled from the Main-Class field in the Manifest.MF file 
	--these tags will be useful for linking malware samples

New module keytool_parse.py in assemblyline/common:
	--with changes to Espresso, it was noted that both APKaye and Espresso use keytool to pull info from the signature block file. Key_tool.py is a small module for the common functionality
	--keytool_parse.py has a minimal class for a certificate called Certificates
	--it has a function to run printcert and return the resulting string or None
	--it also has a module to parse the resulting string and return a list of certificates (using the Certificates class)

2021-04-07 22:43 UTC, cccs-sgaron submitted a review, later dismissed
I don't think this keytool_parse.py belong in base. It really has nothing to do with core components. Since its a central certificate parser that services can use, it should be moved to assemblyline-v4-service.

2021-04-14 13:41 UTC, cccs-rs requested changes

2021-04-14 13:41 UTC, cccs-rs commented on Dockerfile
> +  && apt-get install -yy openjdk-8-jre-headless java-common build-essential libffi-dev libfuzzy-dev \
As @cccs-sgaron pointed out this shouldn't be in the assemblyline-base image, would make more sense to place it in the assemblyline-v4-service image as the base for other services.

2021-04-14 13:50 UTC, cccs-rs commented on Dockerfile
> +  && apt-get install -yy openjdk-8-jre-headless java-common build-essential libffi-dev libfuzzy-dev \
I've added this to the service-base PR, just need to remove it from the assemblyline-base

2021-05-18 13:11 UTC, cccs-rs approved these changes

2021-05-18 13:24 UTC, merged

2021-05-18 13:27 UTC, cccs-sgaron approved these changes