Testing and bugfixes
CybercentreCanada/assemblyline-base pull request #316
Opened 2021-08-03 18:29 UTC by cccs-douglass

- expand unit tests
 - bug fixes/updates related to above
 - removal of dead/unreachable code copied from v3

2021-08-05 14:03 UTC, cccs-sgaron requested changes
Just delete the function instead commenting it

2021-08-05 14:24 UTC, cccs-douglass commented on assemblyline/filestore/transport/local.py
> +    # def getmtime(self, path):
Just an oversight

2021-08-09 11:23 UTC, cccs-rs approved these changes

2021-09-29 19:20 UTC, cccs-sgaron approved these changes

2021-09-29 19:20 UTC, merged